apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    io.kompose.service: dbdata
  name: mssql-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: default
  nfs:
    path: /mnt/k8s-shared/mssql
    server: 10.1.1.253
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
