apiVersion: v1
kind: Service
metadata:
  namespace: blazedesk
  name: blazedesk-idp
  labels:
    app: blazedesk
spec:
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 443
    targetPort: 443
    name: "https"
  selector:
    app: blazedesk
    tier: idp
  type: LoadBalancer
