apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blazedesk
  labels:
    io.kompose.service: codescu-idp-sts-identity
  name: codescu-idp-sts-identity
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: codescu-idp-sts-identity
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: codescu-idp-sts-identity
    spec:
      hostAliases:
      - ip: "10.1.1.253"
        hostnames:
        - "dev.codescu.com"
        - "idp.codescu.com"
        - "admin.codescu.com"
      containers:
      - env:
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+80

        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /app/tls/codescu.com.pfx

        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: ASPNETCORE_Kestrel__Certificates__Default__Password

        - name: CertificateConfiguration__UseTemporarySigningKeyForDevelopment
          value: "false"

        - name: CertificateConfiguration__UseSigningCertificatePfxFile
          value: "true"

        - name: CertificateConfiguration__SigningCertificatePfxFilePath
          value: /app/tls/codescu.com.pfx

        - name: CertificateConfiguration__SigningCertificatePfxFilePassword
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: ASPNETCORE_Kestrel__Certificates__Default__Password

        - name: AdminConfiguration__IdentityAdminBaseUrl
          value: https://admin.codescu.com

        - name: ConnectionStrings__ConfigurationDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__IdentityDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__PersistedGrantDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: SendgridConfiguration__ApiKey
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: SendgridConfiguration__ApiKey
        image: mihaimyh/codescu.idp:latest
        imagePullPolicy: Always
        name: skoruba-identityserver4-sts-identity
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: blazedesk-storage
          mountPath: "/app/tls"
        - name: tz-config
          mountPath: /etc/localtime
        - name: ca-pemstore
          mountPath: /etc/ssl/certs/ca.pem
          subPath: ca.pem
          readOnly: false
      volumes:
      - name: blazedesk-storage
        persistentVolumeClaim:
          claimName: blazedesk-persistent-storage
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Bucharest
      - name: ca-pemstore
        configMap:
          name: ca-pemstore
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
