apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blazedesk
  labels:
    io.kompose.service: codescu-idp-sts-identity
  name: codescu-idp-sts-identity
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: codescu-idp-sts-identity
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: codescu-idp-sts-identity
    spec:
      hostAliases:
      - ip: "10.190.26.240"
        hostnames:
        - "dev.codescu.com"
      - ip: "10.190.26.244"
        hostnames:
        - "idp.codescu.com"
      - ip: "10.190.26.242"
        hostnames:
        - "admin.codescu.com"
      containers:
      - env:
        - name: ASPNETCORE_URLS
          value: https://+:443
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: ASPNETCORE_Kestrel__Certificates__Default__Password
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /app/tls/wildcard.codescu.com.pfx
        - name: AdminConfiguration__IdentityAdminBaseUrl
          value: https://admin.codescu.com
        - name: ConnectionStrings__ConfigurationDbConnection
          value: Server=10.190.26.243;Database=IdentityServer4Admin1;User Id=sa;Password=Password_123;MultipleActiveResultSets=true
        - name: ConnectionStrings__IdentityDbConnection
          value: Server=10.190.26.243;Database=IdentityServer4Admin1;User Id=sa;Password=Password_123;MultipleActiveResultSets=true
        - name: ConnectionStrings__PersistedGrantDbConnection
          value: Server=10.190.26.243;Database=IdentityServer4Admin1;User Id=sa;Password=Password_123;MultipleActiveResultSets=true
        - name: SendgridConfiguration__ApiKey
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: SendgridConfiguration__ApiKey
        image: mihaimyh/codescu.idp:latest
        imagePullPolicy: Always
        name: skoruba-identityserver4-sts-identity
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: blazedesk-storage
          mountPath: "/app/tls"
        - name: tz-config
          mountPath: /etc/localtime
      volumes:
      - name: blazedesk-storage
        persistentVolumeClaim:
          claimName: blazedesk-persistent-storage
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Bucharest
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
