apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: blazedesk
  labels:
    io.kompose.service: codescu-idp-admin
  name: codescu-idp-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: codescu-idp-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: codescu-idp-admin
    spec:
      hostAliases:
      - ip: "10.1.1.253"
        hostnames:
        - "dev.codescu.com"
        - "idp.codescu.com"
        - "admin.codescu.com"
      containers:
      - args:
        - dotnet
        - Codescu.IDP.Admin.dll
        - /seed
        env:
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+80
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: kestrel-cert-pass
              key: ASPNETCORE_Kestrel__Certificates__Default__Password

        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /app/tls/codescu.com.pfx

        - name: AdminConfiguration__IdentityAdminBaseUrl
          value: https://admin.codescu.com
        - name: AdminConfiguration__IdentityAdminRedirectUri
          value: https://admin.codescu.com/signin-oidc
        - name: AdminConfiguration__IdentityServerBaseUrl
          value: https://idp.codescu.com
        - name: AdminConfiguration__RequireHttpsMetadata
          value: "true"
        - name: ConnectionStrings__AdminAuditLogDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__AdminLogDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__ConfigurationDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__IdentityDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: ConnectionStrings__PersistedGrantDbConnection
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin

        - name: IdentityServerData__Clients__0__AllowedCorsOrigins__0
          value: https://admin.codescu.com
        - name: IdentityServerData__Clients__0__ClientUri
          value: https://admin.codescu.com
        - name: IdentityServerData__Clients__0__FrontChannelLogoutUri
          value: https://admin.codescu.com/signin-oidc
        - name: IdentityServerData__Clients__0__PostLogoutRedirectUris__0
          value: https://admin.codescu.com/signout-callback-oidc
        - name: IdentityServerData__Clients__0__RedirectUris__0
          value: https://admin.codescu.com/signin-oidc

        - name: Serilog__WriteTo__1__Args__connectionString
          valueFrom:
            secretKeyRef:
              name: idp-connection-strings
              key: identityserveradmin
        image: mihaimyh/codescuadminui:latest
        imagePullPolicy: Always
        name: skoruba-identityserver4-admin
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: blazedesk-storage
          mountPath: "/app/tls"
        - name: tz-config
          mountPath: /etc/localtime
        - name: ca-pemstore
          mountPath: /etc/ssl/certs/ca.pem
          subPath: ca.pem
          readOnly: false
      volumes:
      - name: blazedesk-storage
        persistentVolumeClaim:
          claimName: blazedesk-persistent-storage
      - name: tz-config
        hostPath:
          path: /usr/share/zoneinfo/Europe/Bucharest
      - name: ca-pemstore
        configMap:
          name: ca-pemstore
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
