apiVersion: v1
kind: Service
metadata:
  namespace: blazedesk
  labels:
    io.kompose.service: codescu-idp-admin
  name: codescu-idp-admin
spec:
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 443
    targetPort: 443
    name: "https"
  selector:
    io.kompose.service: codescu-idp-admin
  type: LoadBalancer

