pipeline {
    agent none
    stages {
        stage('Checkout source code once on master') {
            agent {
                label "master"
            }
            steps {
                git credentialsId: 'github', url: 'https://github.com/codescu/Codescu.IDP.git'
            }
        }
        
        stage('Build'){
            parallel {
                stage('Build Codescu.IDP.Admin docker image') {
                    agent {
                        label "master"
                    }
                    steps {
                        sh 'docker build -t mihaimyh/codescuadminui:latest -f src/Codescu.IDP.Admin/Dockerfile .'
                        withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerPass', usernameVariable: 'dockerUser')]) {
                            sh "docker login -u ${dockerUser} -p ${dockerPass}"
                        }
                        sh 'docker push mihaimyh/codescuadminui:latest'
                    }

                }
            }
        }

        stage('Apply kubernetes scripts and remove docker images'){
            parallel {
                stage('Apply k8s scripts') {
                    agent {
                        label "master"
                    }
                    steps {
                        sh 'kubectl delete -f k8s/7_idsrv_admin_deploy.yaml'
                        sh 'kubectl create -f k8s/7_idsrv_admin_deploy.yaml'
                    }
                }

                stage('Clean-up docker') {
                    agent {
                        label "master"
                    }
                    steps {
                        sh 'docker image rm mihaimyh/codescuadminui'
                        // sh 'docker rmi $(docker images -f "dangling=true" -q)'
                    }
                }
                
            }
            
        }
    }
}